name: "Lint code and run tests"

on:
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.24.5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Install Go"
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Install dependencies"
        run: go mod download
      - name: "Tidy code"
        run: go mod tidy -diff
      - name: "Verify dependencies"
        run: go mod verify
      - name: "Vet code"
        run: go vet ./...
      - uses: dominikh/staticcheck-action@v1
        name: "Run staticcheck"
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ env.GO_VERSION }}
      - uses: golang/govulncheck-action@v1
        name: "Run govulncheck"
        with:
          go-version-input: ${{ env.GO_VERSION }}
      - name: "Run tests"
        run: go test -race -vet=off ./...
