name: "Lint code and run tests"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23.x' ]

    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Install Go"
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: ${{ matrix.go }}
      - name: "Install dependencies"
        run: go mod download
      - name: "Tidy code"
        run: go mod tidy -diff
      - name: "Verify dependencies"
        run: go mod verify
      - name: "Vet code"
        run: go vet ./...
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.go }}
      - name: "Run tests"
        run: go test -race -vet=off ./...
